language: objective-c
sudo: false
install:
    - . $HOME/.nvm/nvm.sh
    - nvm install stable
    - nvm use stable
    - npm install
    - npm install ios-deploy
    - npm install -g codecov
script:
    - npm run jshint
    - npm run unit-tests
    - npm run e2e-tests
    - npm run objc-tests
    - npm run cover
after_script: codecov
